In [1]:
import numpy as np

In [2]:
X=np.linspace(0,20)
a=-1
b=2
y=a*X+b 

In [34]:
def single_variable_GD(X,y,learning_rate,epochs,bathch_size):
    data=np.concatenate((X.reshape(-1,1),y.reshape(-1,1)),axis=1)
    np.random.shuffle(data)
    X_shuffled=data[:,0]
    y_shuffled=data[:,1]

    thetas_0=[]
    thetas_1=[]
    theta_0=0
    theta_1=0

    epoch_loss=[]
    loss=[]
    m=len(X_shuffled)

    for epoch in range(epochs):
        for i in range(0,m,bathch_size):
            h_x=theta_0+theta_1*X_shuffled[i:i+bathch_size]
            error=h_x-y_shuffled[i:i+bathch_size]
            j=1/2 * np.sum(error**2) /len(X_shuffled[i:i+bathch_size])

            thetas_0.append(theta_0)
            thetas_1.append(theta_1)
            loss.append(j)

            d_theta_0=np.sum(error)/len(y_shuffled[i:i+bathch_size])
            d_theta_1=np.sum(error*X_shuffled[i:i+bathch_size])/len(y_shuffled[i:i+bathch_size])

            gradient_vector=np.array([[d_theta_0],[d_theta_1]])
            Norm=np.linalg.norm(gradient_vector)
            theta_0=theta_0-learning_rate*d_theta_0
            theta_1=theta_1-learning_rate*d_theta_1
        epoch_loss.append(j)

        print("****************** Epoch ",epoch,"******************")
        print("j =",j,"\n")
        print("Gradient Vector:\n",gradient_vector,"\n")
        print("Gradiant Vector Norm:\n",Norm,"\n")
        print("theta_0_new:",theta_0)
        print("theta_1_new:",theta_1)

        if Norm <0.001 or abs(epoch_loss[epoch]-epoch_loss[epoch-1])<0.001 and epoch!=0:
            print("****************** Training Report ******************\n")
            print("Gradient Descent converged after ",epoch," epochs\n")
            print("theta_0_Opt:",theta_0)
            print("theta_1_Opt:",theta_1,"\n")
            print("Cost = ",j,"\n")
            break

    return thetas_0,thetas_1,loss,theta_0,theta_1,X_shuffled,y_shuffled


In [35]:
single_variable_GD(X,y,0.0005,300,len(X))

****************** Epoch  0 ******************
j = 49.34693877551022 

Gradient Vector:
 [[  8.        ]
 [114.69387755]] 

Gradiant Vector Norm:
 114.97254258164628 

theta_0_new: -0.004
theta_1_new: -0.05734693877551021
****************** Epoch  1 ******************
j = 42.9613798297648 

Gradient Vector:
 [[  7.42253061]
 [106.929596  ]] 

Gradiant Vector Norm:
 107.18690433895927 

theta_0_new: -0.007711265306122449
theta_1_new: -0.11081173677634318
****************** Epoch  2 ******************
j = 37.41136489517328 

Gradient Vector:
 [[ 6.88417137]
 [99.69110239]] 

Gradiant Vector Norm:
 99.92851300714297 

theta_0_new: -0.011153350989587672
theta_1_new: -0.16065728797303844
****************** Epoch  3 ******************
j = 32.5875614778742 

Gradient Vector:
 [[ 6.38227377]
 [92.94279097]] 

Gradiant Vector Norm:
 93.16166492307666 

theta_0_new: -0.014344487874227686
theta_1_new: -0.20712868345664098
****************** Epoch  4 ******************
j = 28.39494344557049 

Grad

([0,
  -0.004,
  -0.007711265306122449,
  -0.011153350989587672,
  -0.014344487874227686,
  -0.01730167221300737,
  -0.020040749291754,
  -0.022576491371337694,
  -0.024922670351696388,
  -0.027092125515135998,
  -0.02909682668213164,
  -0.030947933090290116,
  -0.032655848286096294,
  -0.03423027129945306,
  -0.03568024435273991,
  -0.0370141973390685,
  -0.0382399892885216,
  -0.0393649470263456,
  -0.04039590121325442,
  -0.04133921994512519,
  -0.04220084007736086,
  -0.042986296428002765,
  -0.04370074900324178,
  -0.04434900837924888,
  -0.04493555936517716,
  -0.04546458306373238,
  -0.04593997743782685,
  -0.04636537648448297,
  -0.04674416811030196,
  -0.04707951079642623,
  -0.04737434913496954,
  -0.04763142831333784,
  -0.047853307617688426,
  -0.04804237302195031,
  -0.04820084892433043,
  -0.04833080908903714,
  -0.04843418684704262,
  -0.04851278460606132,
  -0.048568282716523546,
  -0.04860224773715537,
  -0.048616140140823015,
  -0.04861132149854614,
  -0.0485890611770